# Permalinks
#
markdown: kramdown
permalink: pretty

# Setup
title: "MOK's Onomatomaniske Kaos"

# Onomato·mani, gr., Navnetvang, sygelig Trang til at lede efter Ord,
# som man ikke kan komme paa;

#title: mok0
#tagline: "MOK's Okygraphiske Kaos"

description: >
  <i>“When you are a Bear of Very Little Brain, and you Think of
  Things, you find sometimes that a Thing which seemed very Thingish
  inside you is quite different when it gets out into the open and has
  other people looking at it.” &mdash; A.A. Milne, Winnie-the-Pooh</i>

url: http://mok0.github.io/lanyon
# baseurl: ''
paginate: 2

# About/contact
name: Morten Kjeldgaard
twitter_username: mortenkj
# github_username: mok0
email: "&#109;&#111;&#114;&#116;&#101;&#110;&#107;&#106;&#101;&#108;&#100;&#103;&#097;&#097;&#114;&#100;&#064;&#103;&#109;&#097;&#105;&#108;&#046;&#099;&#111;&#109;"

# Modules needed
gems: [jekyll-paginate]
