# Permalinks
#
markdown: redcarpet
permalink: pretty

# Setup
title: "MOK's Onomatomaniske Kaos"

# Onomato·mani, gr., Navnetvang, sygelig Trang til at lede efter Ord,
# som man ikke kan komme paa;

#title: mok0
#tagline: "MOK's Okygraphiske Kaos"

description: >
  Ikke Medium

url: http://mok0.github.io/lanyon
# baseurl: ''
paginate: 2

# About/contact
name: Morten Kjeldgaard
twitter_username: mortenkj
github_username: mok0
email: mortenkjeldgaard@gmail.com

# Modules needed
gems: [jekyll-paginate]
